Vagrant.configure(2) do |config|
  
  config.vm.box = "laravel/homestead"
  config.vm.box_version = "8.1.0"

  config.vm.network "private_network", ip: "192.168.50.89"

  config.vm.synced_folder "../dev_box", "/vagrant", :owner => 'vagrant', :group => 'www-data'
  config.vm.synced_folder "../html", "/var/www/html", :owner => 'vagrant', :group => 'www-data'

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

end